from __future__ import annotations

from collections.abc import Iterable, Mapping

from recommendations.expanded_catalog import ATTRIBUTE_NAMES as EXPANDED_ATTRIBUTE_NAMES
from recommendations.expanded_catalog import EXPANDED_FOODS
from recommendations.food_details import COLD_SCORES, FOOD_DETAILS

ATTRIBUTE_NAMES = (
    "spicy",
    "broth",
    "light",
    "protein",
    "adventurous",
    "cold",
    "familiar",
    "popularity",
)

LEGACY_NAME_ALIASES = {
    "연어 포케": "연어포케",
}

BASE_ATTRIBUTES = {
    "spicy": 0.0,
    "broth": 0.0,
    "light": 0.4,
    "protein": 0.4,
    "adventurous": 0.2,
    "cold": 0.0,
    "familiar": 0.7,
    "popularity": 0.7,
}


def _group(
    names: Iterable[str],
    *,
    family: str,
    cuisine: str,
    meal_style: str,
    description: str,
    attributes: Mapping[str, float],
    staple_types: tuple[str, ...] = (),
    staple_overrides: Mapping[str, tuple[str, ...]] | None = None,
) -> list[dict[str, object]]:
    overrides = staple_overrides or {}
    foods: list[dict[str, object]] = []
    for name in names:
        detail = FOOD_DETAILS[name]
        individual_attributes = dict(
            zip(
                ATTRIBUTE_NAMES,
                detail.score_values(cold=COLD_SCORES.get(name, 0.0)),
                strict=True,
            )
        )
        foods.append(
            {
                "canonical_name": name,
                "family": family,
                "cuisine": cuisine,
                "meal_style": meal_style,
                "staple_types": list(overrides.get(name, staple_types)),
                "description": detail.description or description,
                "attributes": {
                    **BASE_ATTRIBUTES,
                    **attributes,
                    **individual_attributes,
                },
                "is_lunch_suitable": True,
                "is_active": True,
            }
        )
    return foods


BASE_FOODS = tuple(
    [
        *_group(
            (
                "김치찌개",
                "순두부찌개",
                "된장찌개",
                "부대찌개",
                "청국장찌개",
                "동태찌개",
                "참치김치찌개",
                "꽁치김치찌개",
                "비지찌개",
                "고추장찌개",
                "애호박찌개",
                "두부찌개",
                "차돌된장찌개",
                "스팸김치찌개",
                "돼지고기김치찌개",
                "꽃게탕",
                "알탕",
                "해물탕",
                "버섯전골",
                "만두전골",
                "샤브샤브",
            ),
            family="찌개·전골",
            cuisine="한식",
            meal_style="국물 식사",
            staple_types=("rice",),
            staple_overrides={"샤브샤브": ("rice", "noodle")},
            description="뜨끈한 국물과 건더기를 밥과 함께 즐기는 든든한 한식 메뉴",
            attributes={
                "spicy": 0.55,
                "broth": 0.95,
                "light": 0.3,
                "protein": 0.6,
                "adventurous": 0.2,
                "familiar": 0.92,
                "popularity": 0.83,
            },
        ),
        *_group(
            (
                "설렁탕",
                "곰탕",
                "갈비탕",
                "도가니탕",
                "삼계탕",
                "닭곰탕",
                "육개장",
                "뼈해장국",
                "선지해장국",
                "콩나물국밥",
                "순대국밥",
                "돼지국밥",
                "소머리국밥",
                "굴국밥",
                "황태해장국",
                "미역국정식",
                "소고기무국",
                "떡만둣국",
                "감자탕",
                "추어탕",
                "매생이굴국",
                "사골우거지국",
                "장터국밥",
                "닭개장",
                "오리탕",
            ),
            family="탕·국밥",
            cuisine="한식",
            meal_style="국물 식사",
            staple_types=("rice",),
            staple_overrides={"떡만둣국": ()},
            description="진한 육수와 풍성한 건더기로 속을 채우는 따뜻한 국물 메뉴",
            attributes={
                "spicy": 0.25,
                "broth": 1.0,
                "light": 0.42,
                "protein": 0.72,
                "adventurous": 0.18,
                "familiar": 0.9,
                "popularity": 0.82,
            },
        ),
        *_group(
            (
                "비빔밥",
                "돌솥비빔밥",
                "전주비빔밥",
                "육회비빔밥",
                "회덮밥",
                "제육덮밥",
                "오징어덮밥",
                "낙지덮밥",
                "불고기덮밥",
                "소고기덮밥",
                "닭갈비덮밥",
                "스팸마요덮밥",
                "참치마요덮밥",
                "치킨마요덮밥",
                "꼬막비빔밥",
                "멍게비빔밥",
                "곤드레밥",
                "영양솥밥",
                "김치알밥",
                "날치알밥",
            ),
            family="비빔밥·덮밥",
            cuisine="한식",
            meal_style="한 그릇",
            staple_types=("rice",),
            description="밥과 여러 재료를 한 그릇에 담아 빠르고 든든하게 먹는 메뉴",
            attributes={
                "spicy": 0.38,
                "broth": 0.08,
                "light": 0.46,
                "protein": 0.58,
                "adventurous": 0.22,
                "cold": 0.08,
                "familiar": 0.9,
                "popularity": 0.84,
            },
        ),
        *_group(
            (
                "김치볶음밥",
                "새우볶음밥",
                "깍두기볶음밥",
                "베이컨볶음밥",
                "닭갈비볶음밥",
                "불고기볶음밥",
                "오징어볶음밥",
                "낙지볶음밥",
                "참치김치볶음밥",
                "햄야채볶음밥",
                "계란볶음밥",
                "차돌깍두기볶음밥",
            ),
            family="볶음밥",
            cuisine="한식",
            meal_style="한 그릇",
            staple_types=("rice",),
            description="밥과 재료를 고슬고슬하게 볶아 감칠맛을 살린 한 그릇 메뉴",
            attributes={
                "spicy": 0.35,
                "broth": 0.02,
                "light": 0.25,
                "protein": 0.5,
                "adventurous": 0.12,
                "familiar": 0.95,
                "popularity": 0.85,
            },
        ),
        *_group(
            (
                "제육볶음",
                "돼지불백",
                "소불고기",
                "뚝배기불고기",
                "오삼불고기",
                "닭갈비",
                "춘천닭갈비",
                "간장닭갈비",
                "찜닭",
                "닭볶음탕",
                "돼지갈비",
                "LA갈비",
                "삼겹살",
                "목살구이",
                "고추장삼겹살",
                "보쌈",
                "족발",
                "오리주물럭",
                "오리불고기",
                "훈제오리",
                "떡갈비정식",
                "고등어구이",
                "삼치구이",
                "갈치구이",
                "임연수구이",
            ),
            family="구이·볶음",
            cuisine="한식",
            meal_style="반찬 식사",
            staple_types=("rice",),
            description="고기나 생선을 구우거나 볶아 밥과 곁들이는 단백질 중심 메뉴",
            attributes={
                "spicy": 0.42,
                "broth": 0.08,
                "light": 0.2,
                "protein": 0.9,
                "adventurous": 0.18,
                "familiar": 0.9,
                "popularity": 0.85,
            },
        ),
        *_group(
            (
                "물냉면",
                "비빔냉면",
                "회냉면",
                "칡냉면",
                "막국수",
                "비빔막국수",
                "메밀국수",
                "잔치국수",
                "비빔국수",
                "열무국수",
                "콩국수",
                "칼국수",
                "바지락칼국수",
                "들깨칼국수",
                "닭칼국수",
                "장칼국수",
                "수제비",
                "들깨수제비",
                "팥칼국수",
                "김치말이국수",
                "냉면",
            ),
            family="냉면·국수",
            cuisine="한식",
            meal_style="면",
            staple_types=("noodle",),
            description="면과 육수 또는 양념을 취향에 따라 즐기는 친숙한 한식 면 메뉴",
            attributes={
                "spicy": 0.3,
                "broth": 0.58,
                "light": 0.58,
                "protein": 0.32,
                "adventurous": 0.12,
                "cold": 0.48,
                "familiar": 0.92,
                "popularity": 0.82,
            },
        ),
        *_group(
            (
                "떡볶이",
                "라볶이",
                "로제떡볶이",
                "짜장떡볶이",
                "국물떡볶이",
                "즉석떡볶이",
                "김밥",
                "참치김밥",
                "치즈김밥",
                "돈가스김밥",
                "충무김밥",
                "유부초밥",
                "순대",
                "모둠튀김",
                "쫄면",
                "라면",
                "떡라면",
                "만두라면",
                "김치만두",
                "고기만두",
            ),
            family="분식",
            cuisine="한식",
            meal_style="간편식",
            staple_overrides={
                "라볶이": ("noodle",),
                "김밥": ("rice",),
                "참치김밥": ("rice",),
                "치즈김밥": ("rice",),
                "돈가스김밥": ("rice",),
                "충무김밥": ("rice",),
                "유부초밥": ("rice",),
                "쫄면": ("noodle",),
                "라면": ("noodle",),
                "떡라면": ("noodle",),
                "만두라면": ("noodle",),
            },
            description="익숙한 양념과 탄수화물로 빠르게 만족감을 주는 분식 메뉴",
            attributes={
                "spicy": 0.5,
                "broth": 0.24,
                "light": 0.22,
                "protein": 0.35,
                "adventurous": 0.08,
                "familiar": 0.98,
                "popularity": 0.87,
            },
        ),
        *_group(
            (
                "등심돈가스",
                "안심돈가스",
                "치즈돈가스",
                "생선가스",
                "가츠동",
                "규동",
                "오야코동",
                "사케동",
                "에비동",
                "텐동",
                "장어덮밥",
                "일본식카레",
                "카레라이스",
                "하이라이스",
                "돈가스",
            ),
            family="일식 덮밥·돈가스",
            cuisine="일식",
            meal_style="한 그릇",
            staple_types=("rice",),
            description="튀김이나 고기, 생선을 밥과 함께 푸짐하게 즐기는 일식 메뉴",
            attributes={
                "spicy": 0.12,
                "broth": 0.08,
                "light": 0.25,
                "protein": 0.7,
                "adventurous": 0.24,
                "cold": 0.08,
                "familiar": 0.82,
                "popularity": 0.82,
            },
        ),
        *_group(
            (
                "카레우동",
                "우동",
                "유부우동",
                "김치우동",
                "냉모밀",
                "온소바",
                "판모밀",
                "붓카케우동",
                "니쿠우동",
                "에비튀김우동",
            ),
            family="우동·소바",
            cuisine="일식",
            meal_style="면",
            staple_types=("noodle",),
            description="깔끔한 육수나 소스에 굵은 면 또는 메밀면을 곁들인 일식 면 메뉴",
            attributes={
                "spicy": 0.12,
                "broth": 0.62,
                "light": 0.55,
                "protein": 0.32,
                "adventurous": 0.28,
                "cold": 0.35,
                "familiar": 0.78,
                "popularity": 0.76,
            },
        ),
        *_group(
            (
                "돈코츠라멘",
                "미소라멘",
                "쇼유라멘",
                "시오라멘",
                "탄탄멘",
                "츠케멘",
                "야키소바",
                "오코노미야키",
                "타코야키",
                "초밥정식",
                "모둠초밥",
                "연어초밥",
                "참치초밥",
                "회전초밥",
            ),
            family="라멘·일본요리",
            cuisine="일식",
            meal_style="면·정식",
            staple_overrides={
                "돈코츠라멘": ("noodle",),
                "미소라멘": ("noodle",),
                "쇼유라멘": ("noodle",),
                "시오라멘": ("noodle",),
                "탄탄멘": ("noodle",),
                "츠케멘": ("noodle",),
                "야키소바": ("noodle",),
                "초밥정식": ("rice",),
                "모둠초밥": ("rice",),
                "연어초밥": ("rice",),
                "참치초밥": ("rice",),
                "회전초밥": ("rice",),
            },
            description="진한 육수의 면 또는 해산물과 밥을 조합한 인기 일식 메뉴",
            attributes={
                "spicy": 0.28,
                "broth": 0.54,
                "light": 0.38,
                "protein": 0.58,
                "adventurous": 0.38,
                "cold": 0.12,
                "familiar": 0.72,
                "popularity": 0.79,
            },
        ),
        *_group(
            (
                "짜장면",
                "간짜장",
                "삼선짜장",
                "쟁반짜장",
                "짬뽕",
                "백짬뽕",
                "볶음짬뽕",
                "삼선짬뽕",
                "울면",
                "기스면",
                "우육면",
                "탄탄면",
            ),
            family="중화면",
            cuisine="중식",
            meal_style="면",
            staple_types=("noodle",),
            description="불맛과 진한 소스 또는 육수를 살린 중식 면 메뉴",
            attributes={
                "spicy": 0.48,
                "broth": 0.5,
                "light": 0.25,
                "protein": 0.42,
                "adventurous": 0.3,
                "familiar": 0.86,
                "popularity": 0.85,
            },
        ),
        *_group(
            (
                "중화비빔밥",
                "마파두부덮밥",
                "잡채밥",
                "중식볶음밥",
                "게살볶음밥",
                "유산슬밥",
                "고추잡채밥",
                "탕수육",
                "꿔바로우",
                "깐풍기",
                "유린기",
                "라조기",
                "마파두부",
                "양장피",
                "고추잡채",
                "마라탕",
                "마라샹궈",
                "훠궈",
                "딤섬정식",
                "샤오롱바오정식",
            ),
            family="중화밥·요리",
            cuisine="중식",
            meal_style="한 그릇·요리",
            staple_overrides={
                "중화비빔밥": ("rice",),
                "마파두부덮밥": ("rice",),
                "잡채밥": ("rice",),
                "중식볶음밥": ("rice",),
                "게살볶음밥": ("rice",),
                "유산슬밥": ("rice",),
                "고추잡채밥": ("rice",),
                "고추잡채": ("bread",),
                "마라탕": ("noodle",),
            },
            description="강한 불맛과 향신료, 다채로운 식감을 밥과 함께 즐기는 중식 메뉴",
            attributes={
                "spicy": 0.58,
                "broth": 0.18,
                "light": 0.2,
                "protein": 0.62,
                "adventurous": 0.5,
                "familiar": 0.72,
                "popularity": 0.78,
            },
        ),
        *_group(
            (
                "소고기쌀국수",
                "닭고기쌀국수",
                "매운쌀국수",
                "분짜",
                "분보후에",
                "반미",
                "반쎄오",
                "월남쌈",
                "껌승",
                "베트남볶음밥",
                "쌀국수",
            ),
            family="베트남 요리",
            cuisine="베트남식",
            meal_style="면·한 그릇",
            staple_overrides={
                "소고기쌀국수": ("noodle",),
                "닭고기쌀국수": ("noodle",),
                "매운쌀국수": ("noodle",),
                "분짜": ("noodle",),
                "분보후에": ("noodle",),
                "반미": ("bread",),
                "껌승": ("rice",),
                "베트남볶음밥": ("rice",),
                "쌀국수": ("noodle",),
            },
            description="향긋한 허브와 산뜻한 소스로 가볍게 즐기는 베트남식 메뉴",
            attributes={
                "spicy": 0.32,
                "broth": 0.45,
                "light": 0.68,
                "protein": 0.55,
                "adventurous": 0.46,
                "cold": 0.15,
                "familiar": 0.62,
                "popularity": 0.74,
            },
        ),
        *_group(
            (
                "팟타이",
                "팟씨유",
                "똠얌꿍",
                "똠얌쌀국수",
                "카오팟",
                "카오만가이",
                "푸팟퐁커리",
                "그린커리",
                "레드커리",
                "팟카파오무쌉",
            ),
            family="태국 요리",
            cuisine="태국식",
            meal_style="면·한 그릇",
            staple_overrides={
                "팟타이": ("noodle",),
                "팟씨유": ("noodle",),
                "똠얌쌀국수": ("noodle",),
                "카오팟": ("rice",),
                "카오만가이": ("rice",),
                "푸팟퐁커리": ("rice",),
                "그린커리": ("rice",),
                "레드커리": ("rice",),
                "팟카파오무쌉": ("rice",),
            },
            description="매콤하고 새콤한 향신료와 허브 풍미가 선명한 태국식 메뉴",
            attributes={
                "spicy": 0.62,
                "broth": 0.32,
                "light": 0.48,
                "protein": 0.55,
                "adventurous": 0.62,
                "cold": 0.08,
                "familiar": 0.48,
                "popularity": 0.68,
            },
        ),
        *_group(
            (
                "나시고렝",
                "미고렝",
                "락사",
                "하이난치킨라이스",
                "바쿠테",
                "사테라이스",
                "칠리크랩",
                "코코넛커리",
                "싱가포르치킨라이스",
                "렌당덮밥",
            ),
            family="동남아 요리",
            cuisine="동남아식",
            meal_style="한 그릇",
            staple_types=("rice",),
            staple_overrides={
                "미고렝": ("noodle",),
                "락사": ("noodle",),
                "칠리크랩": (),
            },
            description="향신료와 달콤짭짤한 소스를 밥 또는 면과 조합한 동남아식 메뉴",
            attributes={
                "spicy": 0.48,
                "broth": 0.28,
                "light": 0.4,
                "protein": 0.58,
                "adventurous": 0.6,
                "familiar": 0.45,
                "popularity": 0.66,
            },
        ),
        *_group(
            (
                "토마토파스타",
                "알리오올리오",
                "까르보나라",
                "로제파스타",
                "봉골레파스타",
                "해산물파스타",
                "라구파스타",
                "바질페스토파스타",
                "라자냐",
                "버섯리소토",
                "해산물리소토",
                "토마토리소토",
            ),
            family="파스타·리소토",
            cuisine="이탈리아식",
            meal_style="면·한 그릇",
            staple_types=("noodle",),
            staple_overrides={
                "버섯리소토": ("rice",),
                "해산물리소토": ("rice",),
                "토마토리소토": ("rice",),
            },
            description="소스의 풍미를 면이나 쌀에 진하게 입힌 이탈리아식 메뉴",
            attributes={
                "spicy": 0.12,
                "broth": 0.05,
                "light": 0.32,
                "protein": 0.42,
                "adventurous": 0.3,
                "familiar": 0.76,
                "popularity": 0.78,
            },
        ),
        *_group(
            (
                "마르게리타피자",
                "페퍼로니피자",
                "고르곤졸라피자",
                "치즈피자",
                "불고기피자",
                "포테이토피자",
                "하와이안피자",
                "루꼴라피자",
            ),
            family="피자",
            cuisine="이탈리아식",
            meal_style="공유 식사",
            staple_types=("bread",),
            description="구운 도우에 치즈와 토핑을 올린 익숙하고 든든한 메뉴",
            attributes={
                "spicy": 0.1,
                "broth": 0.0,
                "light": 0.16,
                "protein": 0.5,
                "adventurous": 0.18,
                "familiar": 0.9,
                "popularity": 0.82,
            },
        ),
        *_group(
            (
                "스테이크",
                "함박스테이크",
                "찹스테이크",
                "치킨스테이크",
                "그릴드치킨",
                "피시앤칩스",
                "바비큐폭립",
                "미트볼플레이트",
                "치킨커틀릿",
                "연어스테이크",
            ),
            family="양식 메인",
            cuisine="서양식",
            meal_style="플레이트",
            description="구운 단백질과 곁들임을 한 접시에 담은 서양식 메인 메뉴",
            attributes={
                "spicy": 0.08,
                "broth": 0.02,
                "light": 0.28,
                "protein": 0.9,
                "adventurous": 0.26,
                "familiar": 0.72,
                "popularity": 0.76,
            },
        ),
        *_group(
            (
                "비프버거",
                "치즈버거",
                "치킨버거",
                "새우버거",
                "클럽샌드위치",
                "BLT샌드위치",
                "잠봉뵈르",
                "크루아상샌드위치",
                "그릴드치즈샌드위치",
                "에그샌드위치",
                "프렌치토스트",
                "오믈렛",
                "브런치플레이트",
                "치킨파니니",
            ),
            family="버거·샌드위치",
            cuisine="서양식",
            meal_style="간편식",
            staple_types=("bread",),
            staple_overrides={"오믈렛": (), "브런치플레이트": ()},
            description="빵과 속재료를 조합해 간편하지만 든든하게 먹는 서양식 메뉴",
            attributes={
                "spicy": 0.08,
                "broth": 0.0,
                "light": 0.34,
                "protein": 0.62,
                "adventurous": 0.2,
                "cold": 0.12,
                "familiar": 0.85,
                "popularity": 0.79,
            },
        ),
        *_group(
            (
                "연어포케",
                "참치포케",
                "두부포케",
                "닭가슴살포케",
                "치킨샐러드",
                "연어샐러드",
                "리코타치즈샐러드",
                "시저샐러드",
                "콥샐러드",
                "그릭샐러드",
                "두부샐러드",
                "닭가슴살샐러드",
                "샐러드파스타",
                "메밀샐러드",
                "랩샌드위치",
                "치킨랩",
                "부리토볼",
                "아사이볼",
                "그릭요거트볼",
                "단호박샐러드",
            ),
            family="포케·샐러드",
            cuisine="퓨전",
            meal_style="가벼운 한 그릇",
            staple_overrides={
                "연어포케": ("rice",),
                "참치포케": ("rice",),
                "두부포케": ("rice",),
                "닭가슴살포케": ("rice",),
                "샐러드파스타": ("noodle",),
                "메밀샐러드": ("noodle",),
                "랩샌드위치": ("bread",),
                "치킨랩": ("bread",),
                "부리토볼": ("rice",),
            },
            description="채소와 단백질을 산뜻하게 조합해 부담을 줄인 가벼운 메뉴",
            attributes={
                "spicy": 0.08,
                "broth": 0.0,
                "light": 0.92,
                "protein": 0.65,
                "adventurous": 0.35,
                "cold": 0.58,
                "familiar": 0.65,
                "popularity": 0.7,
            },
        ),
        *_group(
            (
                "버터치킨커리",
                "치킨티카마살라",
                "팔락파니르",
                "달커리",
                "탄두리치킨",
                "비리야니",
                "키마커리",
                "난과커리세트",
                "마크니커리",
                "빈달루커리",
            ),
            family="인도 요리",
            cuisine="인도식",
            meal_style="커리·한 그릇",
            staple_types=("rice",),
            staple_overrides={
                "탄두리치킨": (),
                "난과커리세트": ("bread",),
            },
            description="여러 향신료를 층층이 쌓아 밥이나 난과 함께 먹는 인도식 메뉴",
            attributes={
                "spicy": 0.58,
                "broth": 0.18,
                "light": 0.3,
                "protein": 0.6,
                "adventurous": 0.68,
                "familiar": 0.46,
                "popularity": 0.66,
            },
        ),
        *_group(
            (
                "케밥플레이트",
                "치킨샤와르마",
                "팔라펠플레이트",
                "후무스플레이트",
                "샥슈카",
                "램케밥",
                "치킨케밥",
                "쿠스쿠스플레이트",
                "피타샌드위치",
                "터키식필라프",
            ),
            family="중동 요리",
            cuisine="중동식",
            meal_style="플레이트",
            staple_overrides={
                "케밥플레이트": ("rice", "bread"),
                "치킨샤와르마": ("bread",),
                "팔라펠플레이트": ("bread",),
                "후무스플레이트": ("bread",),
                "샥슈카": ("bread",),
                "램케밥": ("rice", "bread"),
                "치킨케밥": ("rice", "bread"),
                "피타샌드위치": ("bread",),
                "터키식필라프": ("rice",),
            },
            description="향신료를 입힌 고기나 콩 요리를 빵과 채소에 곁들이는 메뉴",
            attributes={
                "spicy": 0.28,
                "broth": 0.06,
                "light": 0.52,
                "protein": 0.72,
                "adventurous": 0.7,
                "familiar": 0.38,
                "popularity": 0.58,
            },
        ),
        *_group(
            (
                "비프타코",
                "치킨타코",
                "피쉬타코",
                "부리토",
                "퀘사디아",
                "엔칠라다",
                "나초플레이트",
                "칠리콘카르네",
                "비프파히타",
                "치킨파히타",
                "멕시칸라이스볼",
                "타코샐러드",
            ),
            family="멕시칸",
            cuisine="멕시코식",
            meal_style="한 그릇·간편식",
            staple_overrides={
                "비프타코": ("bread",),
                "치킨타코": ("bread",),
                "피쉬타코": ("bread",),
                "부리토": ("rice", "bread"),
                "퀘사디아": ("bread",),
                "엔칠라다": ("bread",),
                "비프파히타": ("bread",),
                "치킨파히타": ("bread",),
                "멕시칸라이스볼": ("rice",),
            },
            description="또르띠야와 고기, 콩, 살사를 풍성하게 조합한 멕시코식 메뉴",
            attributes={
                "spicy": 0.52,
                "broth": 0.02,
                "light": 0.38,
                "protein": 0.68,
                "adventurous": 0.58,
                "cold": 0.08,
                "familiar": 0.5,
                "popularity": 0.64,
            },
        ),
    ]
)

if ATTRIBUTE_NAMES != EXPANDED_ATTRIBUTE_NAMES:
    raise ValueError("Base and expanded catalogs use different attribute schemas")

FOODS = (*BASE_FOODS, *EXPANDED_FOODS)


def validate_catalog() -> None:
    names = [str(item["canonical_name"]) for item in FOODS]
    if len(names) != 1_000:
        raise ValueError(f"Food seed catalog must contain exactly 1,000 menus: {len(names)}")
    if len(names) != len(set(names)):
        raise ValueError("Food seed catalog contains duplicate canonical names")

    descriptions = [str(item["description"]) for item in FOODS]
    if len(descriptions) != len(set(descriptions)):
        raise ValueError("Food seed catalog contains duplicate descriptions")

    expected_attributes = set(ATTRIBUTE_NAMES)
    for item in FOODS:
        attributes = item["attributes"]
        if not isinstance(attributes, dict) or set(attributes) != expected_attributes:
            raise ValueError(f"Incomplete attributes for {item['canonical_name']}")
        has_invalid_value = any(
            not isinstance(value, int | float) or not 0 <= value <= 1
            for value in attributes.values()
        )
        if has_invalid_value:
            raise ValueError(f"Invalid attribute value for {item['canonical_name']}")
        staples = item["staple_types"]
        if not isinstance(staples, list) or len(staples) != len(set(staples)):
            raise ValueError(f"Invalid staple types for {item['canonical_name']}")


validate_catalog()
