# Generated by Django 5.2.17 on 2026-08-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_food_staple_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('DRAWN', 'Drawn')], db_index=True, default='WAITING', max_length=12)),
                ('result_votes', models.PositiveSmallIntegerField(default=0)),
                ('leading_food_ids', models.JSONField(default=list)),
                ('draw_count', models.PositiveIntegerField(default=0)),
                ('drawn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multi_room_results', to='recommendations.food')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiRoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('normalized_nickname', models.CharField(max_length=20)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('is_host', models.BooleanField(default=False)),
                ('is_ready', models.BooleanField(db_index=True, default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='recommendations.multiroom')),
            ],
            options={
                'ordering': ['joined_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MultiRoomChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='multi_room_choices', to='recommendations.food')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='recommendations.multiroomparticipant')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='multiroomparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'normalized_nickname'), name='unique_multi_room_nickname'),
        ),
        migrations.AddConstraint(
            model_name='multiroomparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_host', True)), fields=('room',), name='unique_multi_room_host'),
        ),
        migrations.AddConstraint(
            model_name='multiroomchoice',
            constraint=models.UniqueConstraint(fields=('participant', 'food'), name='unique_multi_participant_food'),
        ),
    ]
