# Generated by Django 5.2.17 on 2026-08-18 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0005_multiroom_multiroomparticipant_multiroomchoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiroom",
            name="leading_choice_keys",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="multiroomchoice",
            name="food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="multi_room_choices",
                to="recommendations.food",
            ),
        ),
        migrations.CreateModel(
            name="MultiRoomCustomFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("normalized_name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_foods",
                        to="recommendations.multiroom",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="multiroom",
            name="result_custom_food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="result_rooms",
                to="recommendations.multiroomcustomfood",
            ),
        ),
        migrations.AddField(
            model_name="multiroomchoice",
            name="custom_food",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="recommendations.multiroomcustomfood",
            ),
        ),
        migrations.AddConstraint(
            model_name="multiroomchoice",
            constraint=models.UniqueConstraint(
                fields=("participant", "custom_food"), name="unique_multi_participant_custom_food"
            ),
        ),
        migrations.AddConstraint(
            model_name="multiroomchoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("custom_food__isnull", True), ("food__isnull", False)),
                    models.Q(("custom_food__isnull", False), ("food__isnull", True)),
                    _connector="OR",
                ),
                name="multi_choice_has_exactly_one_food_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="multiroomcustomfood",
            constraint=models.UniqueConstraint(
                fields=("room", "normalized_name"), name="unique_multi_room_custom_food"
            ),
        ),
    ]
